export const queryKeys = {
	auth: "auth",
	users: "users",
	user: "user",
	dashboard: "dashboard",
	province: "province",
	amphure: "amphure",
	district: "district",
	zipcode:"zipcode",
	employee:"employee",
	employees:"employees",
	withdraw:"withdraw",
	withdraws:"withdraws",
	unit:"unit",
	units:"units",
	material:"material",
	materials:"materials",
	category:"category",
	categorys:"categorys",
	org:"org",
	orgs:"orgs",
	report:"report",
	reports:"reports",
};
